import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import { WifiOff, Wifi } from 'lucide-react';

/**
 * Listens for offline/online events and registers the PWA service worker.
 * Renders nothing — just a side-effect component.
 */
export const PWAStatus = () => {
  const [online, setOnline] = useState(typeof navigator !== 'undefined' ? navigator.onLine : true);

  useEffect(() => {
    const goOnline = () => {
      setOnline(true);
      toast.success('Back online', { icon: <Wifi className="h-4 w-4" /> });
    };
    const goOffline = () => {
      setOnline(false);
      toast.warning('You are offline · cached files still viewable', { icon: <WifiOff className="h-4 w-4" /> });
    };
    window.addEventListener('online', goOnline);
    window.addEventListener('offline', goOffline);
    return () => {
      window.removeEventListener('online', goOnline);
      window.removeEventListener('offline', goOffline);
    };
  }, []);

  // Register the service worker generated by vite-plugin-pwa.
  useEffect(() => {
    if (typeof window === 'undefined') return;
    if (!('serviceWorker' in navigator)) return;
    // Dynamic import so the module only loads in the browser.
    import('virtual:pwa-register')
      .then(({ registerSW }) => {
        registerSW({
          immediate: true,
          onRegisteredSW(_swUrl, registration) {
            // Auto-update once an hour
            if (registration) {
              setInterval(() => registration.update().catch(() => {}), 60 * 60 * 1000);
            }
          },
          onNeedRefresh() {
            toast.info('New version available · refresh to update', {
              action: { label: 'Refresh', onClick: () => window.location.reload() },
              duration: 10000,
            });
          },
          onOfflineReady() {
            console.info('[PWA] Ready to work offline');
          },
        });
      })
      .catch(() => {
        // dev mode or plugin not loaded — fine
      });
  }, []);

  if (online) return null;

  return (
    <div className="fixed top-2 left-1/2 -translate-x-1/2 z-50 px-3 py-1.5 rounded-full bg-yellow-500/20 border border-yellow-500/40 text-yellow-700 dark:text-yellow-300 text-xs font-mono flex items-center gap-2 backdrop-blur-md">
      <WifiOff className="h-3 w-3" />
      Offline
    </div>
  );
};
